# VERSION=latest

version: "3.6"

services:

  backend:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    networks:
      - internal-subnet
    ports:
      - 3080:3080
      - 3000:3000
    environment:
      - SIGNUP_API_URL=http://signup:5000/api
      - DB_HOST=dbbackend
      - DB_PORT=5432
      - DB_NAME=backend
      - DB_USERNAME=backend
      - DB_PASSWORD=Pa55w0rd
      - AUTH_SERVER_URL=http://keycloak:8080/auth
      - REALM=local.app
      - CLIENT_ID=local.backend.bearer
      - CLIENT_SECRET=3ce3d1c5-ab8f-412d-9880-217cfa2f2e7a
    volumes:
#      - ./config/backend.env:/code/app/config/db.env:ro
      - .:/code/app
      - /code/app/node_modules
      - backend_files:/data/files:rw
      - backend_logs:/data/logs:rw
    command: npm run start

  db:
    image: postgres:13.1
    container_name: dbbackend
    hostname: dbbackend
    networks:
      - internal-subnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbbackend_data:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak
    hostname: keycloak
    networks:
      - internal-subnet
    ports:
      - "1080:8080"
      - "1443:8443"
    depends_on:
      - dbkeycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbkeycloak
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Pa55w0rd
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./config/keycloak/:/opt/jboss/keycloak/imports/:rw
    command:
      - "-Dkeycloak.profile.feature.docker=enabled"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.dir=/opt/jboss/keycloak/imports/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    restart: unless-stopped

  dbkeycloak:
    image: postgres:13.1
    container_name: dbkeycloak
    hostname: dbkeycloak
    networks:
      - internal-subnet
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=Pa55w0rd
    volumes:
      - dbkeycloak_data:/var/lib/postgresql/data
    restart: always

networks:
  internal-subnet:
    name: internal_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24

volumes:  
  backend_files:
  backend_logs:
  backend_data:
  dbbackend_data:
  dbkeycloak_data:
